spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

kafka:
  url: "127.0.0.1:9092"
  consumer:
    groupid: "groupId"
    topics: mytopic #put comma separated topics names

productrestapi:
  services:
    url: http://localhost:8082

server:
  port: '8082'
